### ISSUE TITLE
Unable to disable sequencing when creating a model

### ISSUE THREAD

**Issue by ehamrin** [gurgentil/laravel-eloquent-sequencer#11]
It should be possible to disable sequencing when creating a model by calling 
```
(new Model($attributes))
    ->withoutSequencing()
    ->save();
```

#### Use case
When migrating data between two systems the order column is already populated and I have no need to recalculate the order.

**Comment by gurgentil** [comment]
I hope the latest release works for you! :) #15

**Comment by ehamrin** [comment]
The latest release requires a modification to the global config each time I need to disable a single sequencing for a specific model.

It seems like a better solution to add the following lines to the handleSequencableCreate method like the others:
```php
 if (! $this->shouldBeSequenced) {
     $this->shouldBeSequenced = true;

     return;
}

```
