### ISSUE TITLE
remove static keyword in documentation example

### ISSUE THREAD

**Issue by lrathbun** [gurgentil/laravel-eloquent-sequencer#5]
**$fillable** is not defined as static so I don't think it should be indicated as such in your example.
[https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php)

Thanks for such a great trait!

**Comment by gurgentil** [comment]
Thank you so much, @lrathbun !
